version: '3.9'

services:
        db:
                build:
                        context: .
                        dockerfile: ./postgresql/Dockerfile
                        args:
                                - DB_LANG=ja_JP
                container_name: postgres_mattermost
                restart: ${RESTART_POLICY}
                security_opt:
                        - no-new-privileges:true
                pids_limit: 100
                expose:
                        - 5432
                # volumes:
                #         - type: bind
                #           source: /var/postgresql/docker
                #           target: /host
                #         - type: bind
                #           source: ${POSTGRES_DATA_PATH}
                #           target: /var/lib/postgresql/data
                #         - type: bind
                #           source: ${POSTGRES_DATABK_PATH}
                #           target: /var/lib/postgresql/data_bk
                #         - type: bind
                #           source: ${POSTGRES_SCRIPT_PATH}
                #           target: /docker-entrypoint-initdb.d
                #           read_only: true
                environment:
                        - POSTGRES_USER
                        - POSTGRES_PASSWORD
                        - POSTGRES_DB
        # pgadmin:
        #         depends_on:
        #                 - db
        #         image: dpage/pgadmin4
        #         platform: linux/x86_64
        #         container_name: pgadmin_mattermost
        #         restart: ${RESTART_POLICY}
        #         expose:
        #                 - 80
        #         security_opt:
        #                 - no-new-privileges:true
        #         pids_limit: 100
        #         volumes:
        #                 - type: volume
        #                   source: pgadmin
        #                   target: /var/lib/pgadmin
        #         environment:
        #                 - PGADMIN_DEFAULT_EMAIL
        #                 - PGADMIN_DEFAULT_PASSWORD
        mattermost:
                depends_on:
                        - db
                container_name: mattermost
                # build:
                #         context: .
                #         dockerfile: ./mattermost/Dockerfile
                #         args:
                #                 - MATTERMOST_IMAGE_TAG=${MATTERMOST_IMAGE_TAG}
                #                 - MM_SQLSETTINGS_DRIVERNAME=${MM_SQLSETTINGS_DRIVERNAME}
                #                 - MM_SQLSETTINGS_DATASOURCE=${MM_SQLSETTINGS_DATASOURCE}
                #                 - MM_SERVICESETTINGS_SITEURL=${MM_SERVICESETTINGS_SITEURL}
                #                 - MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION=${MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION}
                #                 - MM_SERVICESETTINGS_ENABLETUTORIAL=${MM_SERVICESETTINGS_ENABLETUTORIAL}
                #                 - MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE=${MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE}
                #                 - MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE=${MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE}
                #                 - MM_TEAMSETTINGS_MAXCHANNELSPERTEAM=${MM_TEAMSETTINGS_MAXCHANNELSPERTEAM}
                #                 - MM_PLUGINSETTINGS_ENABLE=${MM_PLUGINSETTINGS_ENABLE}
                #                 - MM_PLUGINSETTINGS_ENABLEUPLOADS=${MM_PLUGINSETTINGS_ENABLEUPLOADS}
                image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
                platform: linux/x86_64
                restart: ${RESTART_POLICY}
                security_opt:
                        - no-new-privileges:true
                pids_limit: 200
                expose:
                        - 8065
                # tmpfs:
                #         - /tmp
                # volumes:
                #         - type: bind
                #           source: /var/mattermost/docker
                #           target: /host
                #         - type: bind
                #           source: ${MATTERMOST_CONFIG_PATH}
                #           target: /mattermost/config
                #         - type: bind
                #           source: ${MATTERMOST_DATA_PATH}
                #           target: /mattermost/data
                #         - type: bind
                #           source: ${MATTERMOST_LOGS_PATH}
                #           target: /mattermost/logs
                #         - type: bind
                #           source: ${MATTERMOST_PLUGINS_PATH}
                #           target: /mattermost/plugins
                #         - type: bind
                #           source: ${MATTERMOST_CLIENT_PLUGINS_PATH}
                #           target: /mattermost/client/plugins
                #         - type: bind
                #           source: ${MATTERMOST_BLEVE_INDEXES_PATH}
                #           target: /mattermost/bleve-indexes
                environment:
                        - TZ
                        - MM_SQLSETTINGS_DRIVERNAME
                        - MM_SQLSETTINGS_DATASOURCE
                        - MM_SERVICESETTINGS_SITEURL
                        - MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION
                        - MM_SERVICESETTINGS_ENABLETUTORIAL
                        - MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE
                        - MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE
                        - MM_TEAMSETTINGS_MAXUSERSPERTEAM
                        - MM_TEAMSETTINGS_MAXCHANNELSPERTEAM
                        - MM_PLUGINSETTINGS_ENABLE
                        - MM_PLUGINSETTINGS_ENABLEUPLOADS
                        - MM_BLEVESETTINGS_INDEXDIR
                        - MM_BLEVESETTINGS_ENABLEINDEXING
                        - MM_BLEVESETTINGS_ENABLESEARCHING
                        - MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE
                #         - MM_PLUGINSETTINGS_CLIENTDIRECTORY=/opt/mattermost/client/plugins
                # command: |
                #         sh -c
                #         "cp /opt/mattermost/config/config.json /opt/mattermost/config/config.`date +%Y%m%d%H%M%S`.json |
                #         /opt/mattermost/bin/mattermost "
        nginx:
                depends_on:
                        - mattermost
                        # - pgadmin
                container_name: nginx_mattermost
                image: nginx:${NGINX_IMAGE_TAG}
                platform: linux/x86_64
                restart: ${RESTART_POLICY}
                security_opt:
                        - no-new-privileges:true
                pids_limit: 100
                read_only: true
                tmpfs:
                        - /var/run
                        - /var/cache
                # volumes:
                #         - type: bind
                #           source: /var/nginx/docker
                #           target: /host
                #         - type: bind
                #           source: ${NGINX_CONFIG_PATH}
                #           target: /etc/nginx/conf.d
                #           read_only: true
                #         - ${NGINX_DHPARAMS_FILE}:/dhparams4096.pem
                #         - ${CERT_PATH}:/cert.pem:ro
                #         - ${KEY_PATH}:/key.pem:ro
                #         - shared-webroot:/usr/share/nginx/html
                #         - type: bind
                #           source: ${NGINX_LOG_PATH}
                #           target: /var/log/nginx
                environment:
                        - TZ
                ports:
                        - ${HTTPS_PORT}:443
                        - ${HTTP_PORT}:80
                        - 8080:8080
volumes:
        pgadmin:
