name: Build and deploy Docker app to Lightsail
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-1
  AWS_LIGHTSAIL_SERVICE_NAME: container-service-limited-20221031
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client and LightsailControl Plugin
        run: |
          curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl -o lightsailctl
          sudo mv lightsailctl /usr/local/bin/lightsailctl
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pull and Build Docker Image
        run: |
          # docker pull dpage/pgadmin4
          docker pull mattermost/mattermost-enterprise-edition:7.1.2
          docker pull nginx
          docker compose build
          docker image ls
      - name: Delete Image
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail get-container-images --service-name ${service_name} | jq -r --raw-output '.containerImages[] | .image' > image.txt
          while read line; do aws lightsail delete-container-image --image $line --service-name ${service_name}; done < image.txt
      - name: Push Image
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label mmapp-db \
            --image mmapp-db
          # aws lightsail push-container-image \
          #   --region ${{ env.AWS_REGION }} \
          #   --service-name ${service_name} \
          #   --label pgadmin \
          #   --image dpage/pgadmin4
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label mattermost \
            --image mattermost/mattermost-enterprise-edition:7.1.2
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label nginx \
            --image nginx
      - name: Make deploy setting
        run: |
          export $(cat .env | grep -v '^#' | xargs)
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output '.containerImages[] | select(.image | contains("mmapp-db")) | .image' > db_image.txt
          # aws lightsail get-container-images --service-name ${service_name} | jq --raw-output '.containerImages[] | select(.image | contains("pgadmin")) | .image' > pgadmin_image.txt
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output '.containerImages[] | select(.image | contains("mattermost")) | .image' > mm_image.txt
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output '.containerImages[] | select(.image | contains("nginx")) | .image' > nginx_image.txt
          cat container.template.json \
          | jq --arg db_image $(cat db_image.txt) '.containers.db.image=$db_image' \
          | jq --arg mm_image $(cat mm_image.txt) '.containers.mattermost.image=$mm_image' \
          | jq --arg nginx_image $(cat nginx_image.txt) '.containers.nginx.image=$nginx_image' \
          | jq --arg POSTGRES_USER $POSTGRES_USER '.containers.db.environment.POSTGRES_USER=$POSTGRES_USER' \
          | jq --arg POSTGRES_PASSWORD $POSTGRES_PASSWORD '.containers.db.environment.POSTGRES_PASSWORD=$POSTGRES_PASSWORD' \
          | jq --arg POSTGRES_DB $POSTGRES_DB '.containers.db.environment.POSTGRES_DB=$POSTGRES_DB' \
          | jq --arg TZ $TZ '.containers.mattermost.environment.TZ=$TZ' \
          | jq --arg MM_SQLSETTINGS_DRIVERNAME $MM_SQLSETTINGS_DRIVERNAME '.containers.mattermost.environment.MM_SQLSETTINGS_DRIVERNAME=$MM_SQLSETTINGS_DRIVERNAME' \
          | jq --arg POSTGRES_USER $POSTGRES_USER --arg POSTGRES_PASSWORD_ENCODED $POSTGRES_PASSWORD_ENCODED --arg POSTGRES_DB $POSTGRES_DB '.containers.mattermost.environment.MM_SQLSETTINGS_DATASOURCE="postgres://'$POSTGRES_USER':'$POSTGRES_PASSWORD_ENCODED'@localhost:5432/'$POSTGRES_DB'?sslmode=disable&connect_timeout=10"' \
          | jq --arg MM_SERVICESETTINGS_SITEURL $MM_SERVICESETTINGS_SITEURL '.containers.mattermost.environment.MM_SERVICESETTINGS_SITEURL=$MM_SERVICESETTINGS_SITEURL' \
          | jq --arg MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION $MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION '.containers.mattermost.environment.MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION=$MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION' \
          | jq --arg MM_SERVICESETTINGS_ENABLETUTORIAL $MM_SERVICESETTINGS_ENABLETUTORIAL '.containers.mattermost.environment.MM_SERVICESETTINGS_ENABLETUTORIAL=$MM_SERVICESETTINGS_ENABLETUTORIAL' \
          | jq --arg MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE $MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE '.containers.mattermost.environment.MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE=$MM_LOCALIZATIONSETTINGS_DEFAULTSERVERLOCALE' \
          | jq --arg MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE $MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE '.containers.mattermost.environment.MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE=$MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE' \
          | jq --arg MM_TEAMSETTINGS_MAXUSERSPERTEAM $MM_TEAMSETTINGS_MAXUSERSPERTEAM '.containers.mattermost.environment.MM_TEAMSETTINGS_MAXUSERSPERTEAM=$MM_TEAMSETTINGS_MAXUSERSPERTEAM' \
          | jq --arg MM_TEAMSETTINGS_MAXCHANNELSPERTEAM $MM_TEAMSETTINGS_MAXCHANNELSPERTEAM '.containers.mattermost.environment.MM_TEAMSETTINGS_MAXCHANNELSPERTEAM=$MM_TEAMSETTINGS_MAXCHANNELSPERTEAM' \
          | jq --arg MM_PLUGINSETTINGS_ENABLE $MM_PLUGINSETTINGS_ENABLE '.containers.mattermost.environment.MM_PLUGINSETTINGS_ENABLE=$MM_PLUGINSETTINGS_ENABLE' \
          | jq --arg MM_PLUGINSETTINGS_ENABLEUPLOADS $MM_PLUGINSETTINGS_ENABLEUPLOADS '.containers.mattermost.environment.MM_PLUGINSETTINGS_ENABLEUPLOADS=$MM_PLUGINSETTINGS_ENABLEUPLOADS' \
          | jq --arg MM_BLEVESETTINGS_INDEXDIR $MM_BLEVESETTINGS_INDEXDIR '.containers.mattermost.environment.MM_BLEVESETTINGS_INDEXDIR=$MM_BLEVESETTINGS_INDEXDIR' \
          | jq --arg MM_BLEVESETTINGS_ENABLEINDEXING $MM_BLEVESETTINGS_ENABLEINDEXING '.containers.mattermost.environment.MM_BLEVESETTINGS_ENABLEINDEXING=$MM_BLEVESETTINGS_ENABLEINDEXING' \
          | jq --arg MM_BLEVESETTINGS_ENABLESEARCHING $MM_BLEVESETTINGS_ENABLESEARCHING '.containers.mattermost.environment.MM_BLEVESETTINGS_ENABLESEARCHING=$MM_BLEVESETTINGS_ENABLESEARCHING' \
          | jq --arg MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE $MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE '.containers.mattermost.environment.MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE=$MM_BLEVESETTINGS_ENABLEAUTOCOMPLETE' \
          > container.json
          cat container.json
      - name: Deploy
        run: |
          aws lightsail create-container-service-deployment --service-name ${{env.AWS_LIGHTSAIL_SERVICE_NAME}} --cli-input-json file://$(pwd)/container.json
